medikago/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

# static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registrasi_user.urls'), name='registrasi_user'),
    path('', include('obat.urls'), name='obat'),
    path('', include('resep.urls'), name='resep'),
    path('', include('administrator.urls'), name='admin'),
    path('', include('transaksi.urls'), name='transaksi'),
    path('', include('layanan_poliklinik.urls'), name='layanan_poliklinik'),
    path('', include('sesi_konsultasi.urls'), name='sesi_konsultasi'),
    path('', include('rs_cabang.urls'), name='rs_cabang'),
    path('', include('profil.urls'), name='profile'),
]

urlpatterns += staticfiles_urlpatterns()

menu/urls.py
from django.urls import path
from . import views
from .views import *

appname = 'menu'

urlpatterns = [
    path('menu-admin/', menu_admin_view, name='menu admin'),
    path('menu-pasien/', menu_pasien_view, name='menu pasien'),
    path('menu-dokter/', menu_dokter_view, name='menu dokter'),
]

resep/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import addresep_view, daftarresep_view, delete_resep_view

appname = 'resep'

urlpatterns = [
    path('create-resep/', addresep_view, name='create resep'),
    path('daftar-resep/', daftarresep_view, name='daftar resep'),
    url(r'^delete-resep/(?P<slug>[\w-]+)/$', delete_resep_view, name='delete resep')
]

resep/models.py
from django.db import models

# Create your models here.

transaksi/forms.py
from django import forms
from django.db import connection

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

class BuatTransaksiForm(forms.Form):
    no_rekam_medis = forms.ChoiceField(required = True, widget=forms.Select())
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        cursor = connection.cursor()
        cursor.execute('set search_path to medikago;')
        cursor.execute("SELECT no_rekam_medis FROM Pasien;")
        raw_norek = dictfetchall(cursor)
        no_rekam_medis_list = [tuple([row["no_rekam_medis"], row["no_rekam_medis"]]) for row in raw_norek]
        # print(no_rekam_medis_list)
        self.fields['no_rekam_medis'].choices = no_rekam_medis_list

class UpdateTransaksiForm(forms.Form):
    id_transaksi = forms.CharField(label = 'ID Transaksi', widget=forms.TextInput(attrs={
        'readonly' : True,
        'class' : 'read-only',
    }))
    tanggal = forms.DateField(label = 'Tanggal')
    status = forms.CharField(label = 'Status', widget=forms.TextInput())
    total_biaya = forms.CharField(label = 'Total Biaya', widget=forms.TextInput(attrs={
        'readonly' : True,
        'class' : 'read-only',
    }))
    waktu_pembayaran = forms.CharField(label = 'Waktu Pembayaran')
    no_rekam_medis_pasien = forms.CharField(label = 'Nomor Rekam Medis Pasien', 
        widget=forms.TextInput(attrs={'readonly' : True, 'class' : 'read-only',}))
    

resep/views.py
from django.shortcuts import render, redirect
from django.db import connection
from random import randint
from django.http import HttpResponse

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def addresep_view(request):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')

    cursor.execute("select id_konsultasi from sesi_konsultasi;")
    id_konsultasi_rows = dictfetchall(cursor)
    DAFTAR_KONSULTASI = [konsultasi["id_konsultasi"] for konsultasi in id_konsultasi_rows]

    cursor.execute("select id_transaksi from transaksi;")
    id_transaksi_rows = dictfetchall(cursor)
    DAFTAR_TRANSAKSI = [transaksi['id_transaksi'] for transaksi in id_transaksi_rows]

    cursor.execute("select kode from obat;")
    kode_obat_rows = dictfetchall(cursor)
    DAFTAR_OBAT= [kode_obat['kode'] for kode_obat in kode_obat_rows]

    if request.session.get('role') == "ADMIN":
        if request.method == 'POST':
            id_konsultasi = request.POST['id_konsultasi']
            id_transaksi = request.POST['id_transaksi']
            list_kode_obat = []
            number = 0
            while True:
                try:
                    tag = 'form-' + str(number) + '-daftar_kode_obat'
                    kode_obat = str(request.POST[tag])
                    if len(kode_obat) != 0 and kode_obat not in list_kode_obat:
                        list_kode_obat.append(kode_obat)
                    number += 1
                except:
                    break
            # algoritma generate no_resep
            cursor.execute("select no_resep from resep order by length(no_resep), no_resep;")
            res = dictfetchall(cursor)
            no_resep = int(res[len(res) - 1]['no_resep']) + 1
            cursor.execute("insert into resep(no_resep, id_konsultasi, total_harga, id_transaksi) values ('" + str(no_resep) + "', '" + id_konsultasi + "', " + str(0) + ", '" + id_transaksi + "');")
            for kode in list_kode_obat:
                cursor.execute("select bentuk_sediaan from obat where kode='" + str(kode) + "';")
                obatnya = dictfetchall(cursor)
                dosis = str(randint(1, 10)) + " " + obatnya[0]['bentuk_sediaan'].lower()
                aturan = str(randint(1, 4)) + " kali per hari"
                cursor.execute("insert into daftar_obat(no_resep, kode_obat, dosis, aturan) values ('" + str(no_resep) + "', '" + kode + "', '" + dosis + "', '" + aturan + "');")
            return redirect('/daftar-resep/')
        else:
            context = {
                'daftar_konsultasi' : DAFTAR_KONSULTASI,
                'daftar_obat' : DAFTAR_OBAT,
                'daftar_transaksi' : DAFTAR_TRANSAKSI
            }
            return render(request, 'resep/createresep.html', context)
    else:
        html = "<html><body>You are not authorized to view this page.</body></html>"
        return HttpResponse(html)

def daftarresep_view(request):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')

    if request.session.get('role') == "ADMIN":
        role = "admin"
    else:
        role = "others"
    
    cursor.execute("select * from resep order by length(no_resep), no_resep;")
    rows = dictfetchall(cursor)
    cursor.execute("select * from daftar_obat order by length(kode_obat), kode_obat;")
    daftar_obat = dictfetchall(cursor)
    return render(request, 'resep/daftarresep.html', {'rows':rows, 'daftar_obat':daftar_obat, 'role':role})

def delete_resep_view(request, slug):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')

    if request.session.get('role') == "ADMIN":
        cursor.execute("delete from resep where no_resep='" + str(slug) + "';")
        return redirect("/daftar-resep/")
    else:
        html = "<html><body>You are not authorized to view this page.</body></html>"
        return HttpResponse(html)

resep/templates/resep/createresep.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'resep/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'resep/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'resep/style.css' %}">

    <title>Medikago | Buat Resep</title>
</head>

<body>

    {% include 'menu/menuAdmin.html' %}

    <div class = "judul">
        <h1>Form Pembuatan Resep</h1>
    </div>

    <div class="warning">
        <h3>{{error}}</h3>
    </div>

    <div class = "isian">
        <form action="." method="POST">
            
            {% csrf_token %}
            <div class="formulir">
                <p>
                    <label for="id_id_konsultasi">ID Konsultasi:</label>
                    <select name="id_konsultasi" id="id_id_konsultasi">
                        {% for i in daftar_konsultasi %}
                        <option value="{{i}}">{{i}}</option>
                        {% endfor %}
                    </select>
                </p>

                <p>
                    <label for="id_id_transaksi">ID Transaksi:</label>
                    <select name="id_transaksi" id="id_id_transaksi">
                        {% for j in daftar_transaksi %}
                        <option value="{{j}}">{{j}}</option>
                        {% endfor %}
                    </select>
                </p>

                <div class="link_formset">
                    <input type="hidden" name="form-TOTAL_FORMS" value="1" id="id_form-TOTAL_FORMS">
                    <input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS">
                    <input type="hidden" name="form-MIN_NUM_FORMS" value="0" id="id_form-MIN_NUM_FORMS">
                    <input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS">
                    <p>
                        <label for="id_form-0-daftar_kode_obat">Daftar kode obat:</label>
                        <select name="form-0-daftar_kode_obat" id="id_form-0-daftar_kode_obat">
                            {% for k in daftar_obat %}
                            <option value="{{k}}">{{k}}</option>
                            {% endfor %}
                        </select>
                    </p>
                </div>
            </div>

            <a class="add_form" href="#">[tambah]</a>

            <div class="tombol">
                <button type="submit" name="button-submit" class="btn btn-primary">Submit</button>
            </div>

        </form>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
    <script src="{% static 'resep/js/createresep.js' %}"></script>
</body>

</html>

resep/templates/resep/daftarresep.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'resep/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'resep/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'resep/style.css' %}">

    <title>Medikago | Daftar Resep</title>
</head>

<body>

    {% if role == "admin" %}
        {% include 'menu/menuAdmin.html' %}
    {% else %}
        {% include 'menu/menu.html' %}
    {% endif %}

    <div class = "judul">
        <h1>Daftar Resep</h1>
    </div>

    <div class = "tabel">
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">No Resep</th>
                <th scope="col">Total Harga</th>
                <th scope="col">ID Konsultasi</th>
                <th scope="col">ID Transaksi</th>
                <th scope="col">Daftar Obat</th>
                {% if role == "admin" %}
                    <th scope="col">Action</th>
                {% endif %}
              </tr>
            </thead>
            <tbody id="resep">
                {% for resep in rows %}
                <tr>
                    <td>{{ resep.no_resep }}</td>
                    <td>Rp{{ resep.total_harga }}</td>
                    <td>{{ resep.id_konsultasi }}</td>
                    <td>{{ resep.id_transaksi }}</td>
                    <td>
                        {% for obat in daftar_obat %}
                            {% if obat.no_resep == resep.no_resep %}
                                <li>{{ obat.kode_obat }}</li>
                            {% endif %}
                        {% endfor %}
                    </td>
                    {% if role == "admin" %}                    
                        <td>
                            <a href="{% url 'delete resep' slug=resep.no_resep %}" class="btn btn-outline-danger btn-sm" style="margin-bottom: 1%;">delete</a>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
</body>

</html>