medikago/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

# static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registrasi_user.urls'), name='registrasi_user'),
    path('', include('obat.urls'), name='obat'),
    path('', include('resep.urls'), name='resep'),
    path('', include('administrator.urls'), name='admin'),
    path('', include('transaksi.urls'), name='transaksi'),
    path('', include('layanan_poliklinik.urls'), name='layanan_poliklinik'),
    path('', include('sesi_konsultasi.urls'), name='sesi_konsultasi'),
    path('', include('rs_cabang.urls'), name='rs_cabang'),
    path('', include('profil.urls'), name='profile'),
]

urlpatterns += staticfiles_urlpatterns()

menu/urls.py
from django.urls import path
from . import views
from .views import *

appname = 'menu'

urlpatterns = [
    path('menu-admin/', menu_admin_view, name='menu admin'),
    path('menu-pasien/', menu_pasien_view, name='menu pasien'),
    path('menu-dokter/', menu_dokter_view, name='menu dokter'),
]

rs_cabang/urls.py
from django.urls import path
from django.conf.urls import url
from .views import buat_rs_cabang, rs_cabang, update_rs_cabang, daftar_dokter_rscabang, update_dokter_rscabang, dokter_rscabang, delete_rs_cabang, delete_dokter_rscabang

app_name = 'rs_cabang'

urlpatterns = [
	path('buat-rs-cabang/', buat_rs_cabang, name='buat_rs_cabang'),
	path('rs-cabang/', rs_cabang, name='daftar_rs_cabang'),
	url(r'^update-rs-cabang/(?P<slug>[\w-]+)/$', update_rs_cabang, name='update rs'),
    url(r'^delete-rs-cabang/(?P<slug>[\w-]+)/$', delete_rs_cabang, name='delete rs'),
    path('rscabang/daftarkan-dokter/', daftar_dokter_rscabang, name='daftar_dokter_rscabang'),
    path('rscabang/update-dokter/<id>/', update_dokter_rscabang, name='update_dokter_rscabang'),
    path('rscabang/delete-dokter/<id>/', delete_dokter_rscabang, name='delete_dokter_rscabang'),
    path('rscabang/dokter/', dokter_rscabang, name='dokter_rscabang'),
]

rs_cabang/models.py
from django.db import models

# Create your models here.

rs_cabang/forms.py
from django import forms
from django.db import connection

cursor = connection.cursor()
cursor.execute('set search_path to medikago')

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

class BuatRSCabang(forms.Form):
	kode_rs = forms.CharField(label = 'Kode RS', max_length = 50, required = True)
	nama = forms.CharField(label = 'Nama', max_length = 50, required = True)
	tanggal_pendirian = forms.DateField(label = 'Tanggal Pendirian', required = True, widget=forms.DateInput(attrs={
        'placeholder' : 'Day/Month/Year',
        'type' : 'date',
        'required': True,
    }))
	jalan = forms.CharField(label = 'Jalan', required = False)
	kota = forms.CharField(label = 'Kota', required = True)
	nomor = forms.IntegerField(label = 'Nomor', required = False, min_value = 0)

class UpdateRSCabang(forms.Form):
	kode_rs = forms.CharField(label = 'Kode RS', widget=forms.TextInput(attrs={
        'readonly' : True
    }))
	nama = forms.CharField(label = 'Nama', max_length = 50, required = True)
	tanggal_pendirian = forms.DateField(label = 'Tanggal Pendirian', required = True, widget=forms.DateInput(attrs={
        'placeholder' : 'Day/Month/Year',
        'type' : 'date',
        'required': True,
    }))
	jalan = forms.CharField(label = 'Jalan', required = False)
	kota = forms.CharField(label = 'Kota', required = True)
	nomor = forms.IntegerField(label = 'Nomor', required = False, min_value = 0)

class DaftarkanDokter(forms.Form):
	cursor = connection.cursor()
	cursor.execute('set search_path to medikago')
	cursor.execute('select kode_rs from rs_cabang;')
	dict_kode = dictfetchall(cursor)
	KODE_RS = [tuple([row["kode_rs"], row["kode_rs"]]) for row in dict_kode]
	cursor.execute('select id_dokter from dokter;')
	dict_id = dictfetchall(cursor)
	ID_DOKTER = [tuple([row["id_dokter"], row["id_dokter"]]) for row in dict_id]
	id_dokter = forms.CharField(label = 'ID Dokter', widget = forms.Select(choices = ID_DOKTER), required = True)
	kode_rs = forms.CharField(label = 'Kode RS', widget = forms.Select(choices = KODE_RS), required = True)

class UpdateDokter(forms.Form):
	cursor = connection.cursor()
	cursor.execute('set search_path to medikago')
	cursor.execute('select kode_rs from rs_cabang;')
	dict_kode = dictfetchall(cursor)
	KODE_RS = [tuple([row["kode_rs"], row["kode_rs"]]) for row in dict_kode]
	id_dokter = forms.CharField(label = 'ID Dokter', disabled = True, required = False)
	kode_rs = forms.CharField(label = 'Kode RS', widget = forms.Select(choices = KODE_RS), required = True)

rs_cabang/views.py
from django.shortcuts import render, redirect
from .forms import BuatRSCabang, UpdateRSCabang, DaftarkanDokter, UpdateDokter
from django.http import HttpResponse
from django.db import connection

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def buat_rs_cabang(request):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')

    if request.session.get('role') == "ADMIN":
        if request.method == 'POST':
            form = BuatRSCabang(request.POST)
            if form.is_valid():
                kode_rs = form.cleaned_data.get('kode_rs')
                nama = form.cleaned_data.get('nama')
                tanggal_pendirian = form.cleaned_data.get('tanggal_pendirian')
                jalan = form.cleaned_data.get('jalan')
                kota = form.cleaned_data.get('kota')
                nomor = form.cleaned_data.get('nomor')
                try:
                    cursor.execute(f"insert into rs_cabang(kode_rs, nama, tanggal_pendirian, jalan, kota, nomor) values('{kode_rs}', '{nama}','{tanggal_pendirian}','{jalan}','{kota}','{nomor}');")
                    return redirect("/rs-cabang/")
                except:
                    error = "RS Cabang dengan kode " + kode_rs + " sudah ada"
                    response = {'form' : form, 'error' : error}
                    return render(request, 'create-rs-cabang.html', response)
            else:
                error = "Data yang anda masukkan tidak valid"
                response = {'form' : form, 'error' : error}
                return render(request, 'create-rs-cabang.html', response)
        else:
            form = BuatRSCabang()
            response = {'form' : form}
            return render(request, 'create-rs-cabang.html', response)
    else:
        html = "<html><body>You are not authorized to view this page.</body></html>"
        return HttpResponse(html)

def rs_cabang(request):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')

    cursor.execute("select * from rs_cabang")
    rows = dictfetchall(cursor)
    return render(request, 'daftar-rs-cabang.html', {'rows':rows})

def delete_rs_cabang(request, slug):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')

    if request.session.get('role') == "ADMIN":
        cursor.execute("delete from rs_cabang where kode_rs='" + str(slug) + "';")
        return redirect("/rs-cabang/")
    else:
        html = "<html><body>You are not authorized to view this page.</body></html>"
        return HttpResponse(html)

def update_rs_cabang(request, slug):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')

    if request.session.get('role') == "ADMIN":
        if request.method == 'POST':
            form = UpdateRSCabang(request.POST, initial = {
                'kode_rs' : slug
            })
            if form.is_valid():
                nama = form.cleaned_data.get('nama')
                tanggal_pendirian = form.cleaned_data.get('tanggal_pendirian')
                jalan = form.cleaned_data.get('jalan')
                kota = form.cleaned_data.get('kota')
                nomor = form.cleaned_data.get('nomor')
                cursor.execute("update rs_cabang set nama='" + str(nama) + "', tanggal_pendirian='" + str(tanggal_pendirian) + "', jalan='" + str(jalan) + "', kota='" + str(kota) + "', nomor=" + str(nomor) + " where kode_rs='" + str(slug) + "';")
                return redirect("/rs-cabang/")
            else:
                context = {
                    'form' : form
                }
                return render(request, 'update-rs-cabang.html', context)
        else:
            form = UpdateRSCabang(initial = {
                'kode_rs' : slug
            })
            context = {
                'form' : form
            }
            return render(request, 'update-rs-cabang.html', context)
    else:
        html = "<html><body>You are not authorized to view this page.</body></html>"
        return HttpResponse(html)

def daftar_dokter_rscabang(request):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')
    if request.method == 'POST':
        form = DaftarkanDokter(request.POST)
        if form.is_valid():
            id_dokter = form.cleaned_data.get('id_dokter')
            kode_rs = form.cleaned_data.get('kode_rs')
            cursor.execute("insert into dokter_rs_cabang(id_dokter, kode_rs) values('" + str(id_dokter) + "', '" + str(kode_rs) + "');")
            return redirect("/rscabang/dokter/")
        else:
            context = {
                'form' : form
            }
            return render(request, 'daftar_dokter_rscabang.html', context)
    else:
        form = DaftarkanDokter()
        context = {
            'form' : form
        }
        return render(request, 'daftar_dokter_rscabang.html', context)

def dokter_rscabang(request):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')
    cursor.execute("select distinct kode_rs from dokter_rs_cabang")
    rs = dictfetchall(cursor)
    i = 0
    for kode_rs in rs:
        kode_rs['no'] = i+1
        i += 1
        cursor.execute("select id_dokter from dokter_rs_cabang where kode_rs = '" + str(kode_rs.get('kode_rs')) + "';")
        id_dokter = dictfetchall(cursor)
        kode_rs['dokter'] = id_dokter
    if request.session.get('role') == "ADMIN":
        role = "admin"
    else:
        role = "others"
    return render(request, 'dokter_rscabang.html', {'rows':rs, 'role':role})

def update_dokter_rscabang(request, id):
    cursor = connection.cursor()
    cursor.execute('set search_path to medikago')
    if request.session.get('role') == "ADMIN":
        if request.method == 'POST':
            form = UpdateDokter(request.POST)
            if form.is_valid():
                kode_rs = form.cleaned_data.get('kode_rs')
                cursor.execute("update dokter_rs_cabang set kode_rs = '" + str(kode_rs) + "' where id_dokter = '" + str(id) + "';")
                return redirect('/rscabang/dokter/')
            else:
                context = {
                    'form' : form
                }
                return render(request, 'update_dokter_rscabang.html', context)
        else:
            cursor.execute("select * from dokter_rs_cabang where id_dokter = '" + str(id) + "';")
            kode = dictfetchall(cursor)
            form = UpdateDokter(initial = {
                'id_dokter' : str(id),
                'kode_rs' : kode[0].get('kode_rs')
            })
            context = {
                'form' : form
            }
            return render(request, 'update_dokter_rscabang.html', context)
    else:
        html = "<html><body>You are not authorized to view this page.</body></html>"
        return HttpResponse(html)

def delete_dokter_rscabang(request, id):
    if request.session.get('role') == "ADMIN":
        cursor = connection.cursor()
        cursor.execute('set search_path to medikago')
        cursor.execute("delete from dokter_rs_cabang where id_dokter ='" + str(id) + "';")
        return redirect("/rscabang/dokter/")
    else:
        return redirect("/rscabang/dokter/")

rs_cabang/templates/create-rs-cabang.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'obat/style.css' %}">
    
    <title>Medikago | Buat RS Cabang</title>
</head>

<body>

    {% include 'menu/menuAdmin.html' %}

    <div class = "judul">
        <h1>Form Pembuatan RS Cabang</h1>
    </div>

    <div class="warning">
        <h3>{{error}}</h3>
    </div>

    <div class = "isian">
        <form action="." method="POST">
            
            {% csrf_token %}
            <div class="formulir">
                {{form.as_p}}
            </div>

            <div class="tombol">
                <button type="submit" name="button-submit" class="btn btn-primary">Submit</button>
            </div>

        </form>
    </div>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
</body>

</html>

rs_cabang/templates/daftar-rs-cabang.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'obat/style.css' %}">

    <title>Medikago | Daftar RS Cabang</title>
</head>

<body>
    {% if request.session.role == "ADMIN" %}
        {% include 'menu/menuAdmin.html' %}
    {% else %}
        {% include 'menu/menu.html' %}
    {% endif %}

    <div class = "judul">
        <h1>Daftar RS Cabang</h1>
    </div>

    <div class = "tabel">
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Kode RS</th>
                <th scope="col">Nama</th>
                <th scope="col">Tanggal Pendirian</th>
                <th scope="col">Jalan</th>
                <th scope="col">Nomor</th>
                <th scope="col">Kota</th>
                {% if request.session.role == "ADMIN" %}
                    <th scope="col">Action</th>
                {% endif %}
              </tr>
            </thead>
            <tbody id="obat">
                {% for rs in rows %}
                <tr>
                    <td>{{ rs.kode_rs }}</td>
                    <td>{{ rs.nama }}</td>
                    <td>{{ rs.tanggal_pendirian }}</td>
                    <td>{{ rs.jalan }}</td>
                    <td>{{ rs.nomor }}</td>
                    <td>{{ rs.kota }}</td>
                    {% if request.session.role == "ADMIN" %}
                        <td>
                            <a href="{% url 'rs_cabang:update rs' slug=rs.kode_rs %}" class="btn btn-outline-primary btn-sm" style="margin-bottom: 1%;">update</a>
                            <a href="{% url 'rs_cabang:delete rs' slug=rs.kode_rs %}" class="btn btn-outline-danger btn-sm" style="margin-bottom: 1%;">delete</a>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
</body>

</html>

rs_cabang/templates/daftar_dokter_rscabang.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Medikago | Daftarkan Dokter RS Cabang</title>

    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'obat/style.css' %}">
</head>
<body>
    {% include 'menu/menuAdmin.html' %}

    <div class = "judul">
        <h1>Form Pendaftaran Dokter RS Cabang</h1>
    </div>

    <div class = "isian">
        <form action="" method="POST">
            {% csrf_token %}
                <div class="formulir">
                    {{form.as_p}}
                </div>
    
                <div class="tombol">
                    <button type="submit" name="button-submit" class="btn btn-primary">Submit</button>
                </div>
        </form>
    </div>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
</body>
</html>

rs_cabang/templates/dokter_rscabang.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Medikago | Dokter RS Cabang</title>

    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'obat/style.css' %}">
</head>
<body>
    {% if request.session.role == "ADMIN" %}
        {% include 'menu/menuAdmin.html' %}
    {% else %}
        {% include 'menu/menu.html' %}
    {% endif %}
    
    <div class = "judul">
        <h1>Daftar Dokter RS Cabang</h1>
    </div>

    <div class = "tabel">
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">No</th>
                <th scope="col">Kode RS Cabang</th>
                <th scope="col">ID Dokter</th>
                {% if role == "admin" %}
                    <th scope="col">Action</th>
                {% endif %}
              </tr>
            </thead>
            <tbody>
                {% for rs in rows %}
                <tr>
                    <td>{{rs.no}}</td>
                    <td>{{rs.kode_rs}}</td>
                    <td> 
                        {% for doc in rs.dokter %}
                            <p>{{doc.id_dokter}}</p>
                        {% endfor %}
                    </td>
                    {% if role == "admin" %}
                        <td>
                            {% for doc in rs.dokter %}
                            <a href="{% url 'rs_cabang:update_dokter_rscabang' id=doc.id_dokter %}" class="btn btn-outline-primary btn-sm" style="margin-bottom: 1%;">Update</a> <a href="{% url 'rs_cabang:delete_dokter_rscabang' id=doc.id_dokter %}" class="btn btn-outline-secondary btn-sm" style="margin-bottom: 1%;">Delete</a>
                            <br>
                            {% endfor %}
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>

</body>
</html>

rs_cabang/templates/update-rs-cabang.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'obat/style.css' %}">
    
    <title>Medikago | Update RS Cabang</title>
</head>

<body>

    {% include 'menu/menuAdmin.html' %}

    <div class = "judul">
        <h1>Form Update RS Cabang</h1>
    </div>

    <div class = "isian">
        <form action="." method="POST">
            
            {% csrf_token %}
            <div class="formulir">
                {{form.as_p}}
            </div>

            <div class="tombol">
                <button type="submit" name="button-submit" class="btn btn-primary">Submit</button>
            </div>

        </form>
    </div>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
</body>

</html>

rs_cabang/templates/update_dokter_rscabang.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Medikago | Update Dokter RS Cabang</title>

    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'obat/style.css' %}">
</head>
<body>
    {% include 'menu/menuAdmin.html' %}

    <div class = "judul">
        <h1>Form Update Dokter RS Cabang</h1>
    </div>

    <div class = "isian">
        <form action="" method="POST">
            {% csrf_token %}
                <div class="formulir">
                    {{form.as_p}}
                </div>
    
                <div class="tombol">
                    <button type="submit" name="button-submit" class="btn btn-primary">Update</button>
                </div>
        </form>
    </div>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
</body>
</html>