medikago/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

# static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registrasi_user.urls'), name='registrasi_user'),
    path('', include('obat.urls'), name='obat'),
    path('', include('resep.urls'), name='resep'),
    path('', include('administrator.urls'), name='admin'),
    path('', include('transaksi.urls'), name='transaksi'),
    path('', include('layanan_poliklinik.urls'), name='layanan_poliklinik'),
    path('', include('sesi_konsultasi.urls'), name='sesi_konsultasi'),
    path('', include('rs_cabang.urls'), name='rs_cabang'),
    path('', include('profil.urls'), name='profile'),
]

urlpatterns += staticfiles_urlpatterns()

menu/urls.py
from django.urls import path
from . import views
from .views import *

appname = 'menu'

urlpatterns = [
    path('menu-admin/', menu_admin_view, name='menu admin'),
    path('menu-pasien/', menu_pasien_view, name='menu pasien'),
    path('menu-dokter/', menu_dokter_view, name='menu dokter'),
]

rs_cabang/urls.py
from django.urls import path
from django.conf.urls import url
from .views import buat_rs_cabang, rs_cabang, update_rs_cabang, daftar_dokter_rscabang, update_dokter_rscabang, dokter_rscabang, delete_rs_cabang, delete_dokter_rscabang

app_name = 'rs_cabang'

urlpatterns = [
	path('buat-rs-cabang/', buat_rs_cabang, name='buat_rs_cabang'),
	path('rs-cabang/', rs_cabang, name='daftar_rs_cabang'),
	url(r'^update-rs-cabang/(?P<slug>[\w-]+)/$', update_rs_cabang, name='update rs'),
    url(r'^delete-rs-cabang/(?P<slug>[\w-]+)/$', delete_rs_cabang, name='delete rs'),
    path('rscabang/daftarkan-dokter/', daftar_dokter_rscabang, name='daftar_dokter_rscabang'),
    path('rscabang/update-dokter/<id>/', update_dokter_rscabang, name='update_dokter_rscabang'),
    path('rscabang/delete-dokter/<id>/', delete_dokter_rscabang, name='delete_dokter_rscabang'),
    path('rscabang/dokter/', dokter_rscabang, name='dokter_rscabang'),
]

sesi_konsultasi/urls.py
from django.urls import path
from django.conf.urls import url
from .views import sesi_konsultasi, buat_sesi_konsultasi, update_sesi_konsultasi, delete_sesi_konsultasi

app_name = 'sesi_konsultasi'

urlpatterns = [
	path('buat-sesi-konsultasi/', buat_sesi_konsultasi, name='buat_sesi_konsultasi'),
	path('sesi-konsultasi/', sesi_konsultasi, name='daftar_sesi_konsultasi'),
	url(r'^update-sesi-konsultasi/(?P<slug>[\w-]+)/$', update_sesi_konsultasi, name='update_sesi_konsultasi'),
	url(r'^delete-sesi-konsultasi/(?P<slug>[\w-]+)/$', delete_sesi_konsultasi, name='delete_sesi_konsultasi'),
]

menu/models.py
from django.db import models

# Create your models here.

menu/views.py
from django.shortcuts import render

# Create your views here.

menu/templates/menu/menu.html
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">MEDIKAGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto" id="navbarmedikago">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sesi Konsultasi</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'sesi_konsultasi:daftar_sesi_konsultasi' %}">Daftar Sesi Konsultasi</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Poliklinik</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'layanan_poliklinik' %}">Daftar Layanan Poliklinik</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">RS Cabang</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'rs_cabang:daftar_rs_cabang' %}">Daftar RS Cabang</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'rs_cabang:dokter_rscabang' %}">Daftar Dokter RS Cabang</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Resep & Obat</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'daftar resep' %}">Daftar Resep</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'daftar obat' %}">Daftar Obat</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Transaksi</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'daftar transaksi' %}">Daftar Transaksi</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="/profil/{{request.session.username}}/">Profil</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'logout' %}">Sign Out</a>
            </li>
        </ul>
    </div>
</nav>

menu/templates/menu/menuAdmin.html
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">MEDIKAGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto" id="navbarmedikago">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sesi Konsultasi</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'sesi_konsultasi:buat_sesi_konsultasi' %}">Buat Sesi Konsultasi</a>
                    <a class="dropdown-item" href="{% url 'sesi_konsultasi:daftar_sesi_konsultasi' %}">Daftar Sesi Konsultasi</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Poliklinik</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'create_layanan_poliklinik' %}">Buat Layanan Poliklinik</a>
                    <a class="dropdown-item" href="{% url 'layanan_poliklinik' %}">Daftar Layanan Poliklinik</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'create_layanan_poliklinik' %}">Buat Jadwal Poliklinik</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">RS Cabang</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'rs_cabang:buat_rs_cabang' %}">Buat RS Cabang</a>
                    <a class="dropdown-item" href="{% url 'rs_cabang:daftar_rs_cabang' %}">Daftar RS Cabang</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'rs_cabang:daftar_dokter_rscabang' %}">Daftarkan Dokter</a>
                    <a class="dropdown-item" href="{% url 'rs_cabang:dokter_rscabang' %}">Daftar Dokter RS Cabang</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'set admin' %}">Daftarkan Administrator</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Resep & Obat</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'create resep' %}">Buat Resep</a>
                    <a class="dropdown-item" href="{% url 'daftar resep' %}">Daftar Resep</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'create obat' %}">Buat Obat</a>
                    <a class="dropdown-item" href="{% url 'daftar obat' %}">Daftar Obat</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Transaksi</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'buat transaksi' %}">Buat Transaksi</a>
                    <a class="dropdown-item" href="{% url 'daftar transaksi' %}">Daftar Transaksi</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="/profil/{{request.session.username}}/">Profil</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'logout' %}">Sign Out</a>
            </li>
        </ul>
    </div>
</nav>