medikago/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

# static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registrasi_user.urls'), name='registrasi_user'),
    path('', include('obat.urls'), name='obat'),
    path('', include('resep.urls'), name='resep'),
    path('', include('administrator.urls'), name='admin'),
    path('', include('transaksi.urls'), name='transaksi'),
    path('', include('layanan_poliklinik.urls'), name='layanan_poliklinik'),
    path('', include('sesi_konsultasi.urls'), name='sesi_konsultasi'),
    path('', include('rs_cabang.urls'), name='rs_cabang'),
    path('', include('profil.urls'), name='profile'),
]

urlpatterns += staticfiles_urlpatterns()

menu/urls.py
from django.urls import path
from . import views
from .views import *

appname = 'menu'

urlpatterns = [
    path('menu-admin/', menu_admin_view, name='menu admin'),
    path('menu-pasien/', menu_pasien_view, name='menu pasien'),
    path('menu-dokter/', menu_dokter_view, name='menu dokter'),
]

sesi_konsultasi/urls.py
from django.urls import path
from django.conf.urls import url
from .views import sesi_konsultasi, buat_sesi_konsultasi, update_sesi_konsultasi, delete_sesi_konsultasi

app_name = 'sesi_konsultasi'

urlpatterns = [
	path('buat-sesi-konsultasi/', buat_sesi_konsultasi, name='buat_sesi_konsultasi'),
	path('sesi-konsultasi/', sesi_konsultasi, name='daftar_sesi_konsultasi'),
	url(r'^update-sesi-konsultasi/(?P<slug>[\w-]+)/$', update_sesi_konsultasi, name='update_sesi_konsultasi'),
	url(r'^delete-sesi-konsultasi/(?P<slug>[\w-]+)/$', delete_sesi_konsultasi, name='delete_sesi_konsultasi'),
]

sesi_konsultasi/models.py
from django.db import models

# Create your models here.

sesi_konsultasi/forms.py
from django import forms
from django.db import connection

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

class BuatSesiKonsultasi(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        cursor = connection.cursor()
        cursor.execute('set search_path to medikago;')
        cursor.execute('select no_rekam_medis from pasien;')
        dict_nomor_rekam_medis_pasien = dictfetchall(cursor)
        NOMOR_REKAM_MEDIS_CHOICES = [tuple([row['no_rekam_medis'], row['no_rekam_medis']]) for row in dict_nomor_rekam_medis_pasien]
        self.fields['Nomor_Rekam_Medis_Pasien'].choices = NOMOR_REKAM_MEDIS_CHOICES
        cursor = connection.cursor()
        cursor.execute('set search_path to medikago;')
        cursor.execute('select id_transaksi from transaksi;')
        dict_id_transaksi = dictfetchall(cursor)
        ID_TRANSAKSI_CHOICES = [tuple([row['id_transaksi'], row['id_transaksi']]) for row in dict_id_transaksi]
        self.fields['ID_Transaksi'].choices = ID_TRANSAKSI_CHOICES
        
    Nomor_Rekam_Medis_Pasien = forms.ChoiceField(required=True, widget=forms.Select())

    Tanggal = forms.DateField(widget=forms.DateInput(attrs={
        'placeholder' : 'Day/Month/Year',
        'type' : 'date',
        'required': True,
    }))

    ID_Transaksi = forms.ChoiceField(required=True, widget=forms.Select())

class UpdateSesiKonsultasi(forms.Form):
    ID_Konsultasi = forms.CharField(widget=forms.TextInput(attrs={
        'readonly' : True
    }))

    Nomor_Rekam_Medis_Pasien = forms.CharField(widget=forms.TextInput(attrs={
        'readonly' : True
    }))

    Tanggal = forms.DateField(widget=forms.DateInput(attrs={
        'placeholder' : 'Day/Month/Year',
        'type' : 'date',
        'required': True,
    }))

    Biaya = forms.CharField(widget=forms.NumberInput(attrs={
        'readonly' : True
    }))

    Status = forms.CharField(max_length = 50, widget=forms.TextInput(attrs={
        'type' : 'text',
        'required': True,
    }))

    ID_Transaksi = forms.CharField(widget=forms.TextInput(attrs={
        'readonly' : True
    }))

sesi_konsultasi/views.py
from django.shortcuts import render, redirect
from .forms import BuatSesiKonsultasi, UpdateSesiKonsultasi
from django.http import HttpResponse
from django.db import connection

def dictfetchall(cursor):
	columns = [col[0] for col in cursor.description]
	return [
		dict(zip(columns, row))
		for row in cursor.fetchall()
	]

def buat_sesi_konsultasi(request):
	cursor = connection.cursor()
	cursor.execute('set search_path to medikago;')

	if request.session.get('role') == "ADMIN":
		if request.method == 'POST':
			form = BuatSesiKonsultasi(request.POST)

			if form.is_valid():
				cursor.execute('select id_konsultasi from sesi_konsultasi order by id_konsultasi::int desc limit 1;')
				temp = dictfetchall(cursor)
				id_konsultasi = str(int(temp[0]['id_konsultasi']) + 1)
				biaya = 0
				status = "Booked"
				nomor_rekam_medis_pasien = form.cleaned_data['Nomor_Rekam_Medis_Pasien']
				tanggal = form.cleaned_data['Tanggal']
				id_transaksi = form.cleaned_data['ID_Transaksi']
				cursor.execute("insert into sesi_konsultasi values (" + id_konsultasi + ",'" + 
				str(nomor_rekam_medis_pasien) + "','" + str(tanggal) + "','" + str(biaya) + "','" + str(status) + "','" + str(id_transaksi) + "');")
				return redirect('/sesi-konsultasi/')
			else:
				error = "Data yang anda masukkan tidak valid."
				response = {
					'form' : form,
					'error' : error
				}
				return render(request, 'sesi_konsultasi/konsultasi.html', response)
		else:
			form = BuatSesiKonsultasi()
			response = {'form' : form}
			return render(request, 'sesi_konsultasi/konsultasi.html', response)
	else:
		html = "<html><body>You are not authorized to view this page.</body></html>"
		return HttpResponse(html)

def sesi_konsultasi(request):
	cursor = connection.cursor()
	cursor.execute('set search_path to medikago;')
	cursor.execute('select * from sesi_konsultasi;')
	rows = dictfetchall(cursor)

	if request.session.get('role') == "ADMIN":
		role = "admin"
	else:
		role = "others"


	return render(request, 'sesi_konsultasi/daftar-sesi-konsultasi.html', {'rows':rows, 'role':role})

def update_sesi_konsultasi(request, slug):
	cursor = connection.cursor()
	cursor.execute('set search_path to medikago;')

	if request.session.get('role') == "ADMIN":
		if request.method == 'POST':
			form = UpdateSesiKonsultasi(request.POST)
			if form.is_valid():
				id_konsultasi = form.cleaned_data.get('ID_Konsultasi')
				tanggal = form.cleaned_data.get('Tanggal')
				status = form.cleaned_data.get('Status')
				cursor.execute("update sesi_konsultasi set tanggal='" + str(tanggal) + "'," + "status='" + status + "' where id_konsultasi=" + id_konsultasi + "::varchar;")
				return redirect('/sesi-konsultasi/')
			else:
				response = {'form' : form}
				return render(request, 'sesi_konsultasi/update-sesi-konsultasi.html', response)
		else:
			cursor.execute('select no_rekam_medis_pasien, biaya, id_transaksi from sesi_konsultasi where id_konsultasi =' + slug + '::varchar;')
			temp = dictfetchall(cursor)
			nomor_rekam_medis_pasien = temp[0]['no_rekam_medis_pasien']
			biaya = temp[0]['biaya']
			id_transaksi = temp[0]['id_transaksi']
			form = UpdateSesiKonsultasi(initial = {
					'ID_Konsultasi' : slug,
					'Nomor_Rekam_Medis_Pasien' : nomor_rekam_medis_pasien,
					'Biaya' : biaya,
					'ID_Transaksi' : id_transaksi
				})
			response = {'form' : form}
			return render(request, 'sesi_konsultasi/update-sesi-konsultasi.html', response)
	else:
		html = "<html><body>You are not authorized to view this page.</body></html>"
		return HttpResponse(html)

def delete_sesi_konsultasi(request, slug):
	cursor = connection.cursor()
	cursor.execute('set search_path to medikago;')

	if request.session.get('role') == "ADMIN":
		cursor.execute('delete from sesi_konsultasi where id_konsultasi=' + slug + '::varchar;')
		return redirect("/sesi-konsultasi/")
	else:
		html = "<html><body>You are not authorized to view this page.</body></html>"
		return HttpResponse(html)

sesi_konsultasi/templates/sesi_konsultasi/daftar-sesi-konsultasi.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css"  href="{% static 'style.css' %}">

    <title>Medikago | Daftar Sesi Konsultasi</title>

  </head>

  <body>
    {% if role == "admin" %}
      {% include 'menu/menuAdmin.html' %}
    {% else %}
      {% include 'menu/menu.html' %}
    {% endif %}

    <section id = "konsultasi" class = "daftar">
      <div class = "container-fluid">
        <div class = "row">
          <div class = "col d-flex justify-content-center">
            <div class = "judul">
              <h1>Daftar Sesi Konsultasi</h1>
            </div>
          </div>
        </div>

        <div class = "row">
          <div class = "col">
            <div class = "tabel">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">ID Konsultasi</th>
                    <th scope="col">Nomor Pasien</th>
                    <th scope="col">Tanggal</th>
                    <th scope="col">Biaya</th>
                    <th scope="col">Status</th>
                    <th scope="col">ID Transaksi</th>
                    {% if request.session.role == "ADMIN" %}
                      <th scope="col">Action</th>
                    {% endif %}
                  </tr>
                </thead>

                <tbody>
                  {% for konsultasi in rows %}
                    <tr>
                      <td>{{ konsultasi.id_konsultasi }}</td>
                      <td>{{ konsultasi.no_rekam_medis_pasien }}</td>
                      <td>{{ konsultasi.tanggal }}</td>
                      <td>{{ konsultasi.biaya }}</td>
                      <td>{{ konsultasi.status }}</td>
                      <td>{{ konsultasi.id_transaksi }}</td>

                      {% if role == "admin" %}
                        <td><button class='btn btn-dark' onclick="location.href='{% url 'sesi_konsultasi:update_sesi_konsultasi' slug=konsultasi.id_konsultasi %}'">UPDATE</button><button class='btn btn-dark float-right' onclick="location.href='{% url 'sesi_konsultasi:delete_sesi_konsultasi' slug=konsultasi.id_konsultasi %}'">DELETE</button></td>
                      {% endif %}
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/8d51ef034d.js" crossorigin="anonymous"></script>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
  </body>
</html>

sesi_konsultasi/templates/sesi_konsultasi/konsultasi.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'obat/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'obat/style.css' %}">
    
    <title>Medikago | Buat Sesi Konsultasi</title>
</head>

<body>

    {% include 'menu/menuAdmin.html' %}

    <div class = "judul">
        <h1>Form Reservasi Sesi Konsultasi</h1>
    </div>

    <div class="warning">
        <h3>{{error}}</h3>
    </div>

    <div class = "isian">
        <form action="." method="POST">
            
            {% csrf_token %}
            <div class="formulir">
                {{form.as_p}}
            </div>

            <div class="tombol">
                <button type="submit" name="button-submit" class="btn btn-primary">Submit</button>
            </div>

        </form>
    </div>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script>
</body>

</html>

sesi_konsultasi/templates/sesi_konsultasi/update-sesi-konsultasi.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css"  href="{% static 'style.css' %}">

    <title>Medikago | Update Sesi Konsultasi</title>

  </head>

  <body>
    {% include 'menu/menuAdmin.html' %}

    <section id = "konsultasi" class = "registrasi">
      <div class = "container-fluid">
        <div class = "row">
          <div class = "col d-flex justify-content-center">
            <div class = "judul">
              <h1>Form Update Sesi Konsultasi</h1>
            </div>
          </div>
        </div>

        <form action="." method="POST">
        {% csrf_token %}
          <div class = "row">
            <div class = "col">
              ID Konsultasi: {{form.ID_Konsultasi}}
              <br/>
              Nomor Rekam Medis Pasien: {{form.Nomor_Rekam_Medis_Pasien}}
              <br/>
              Tanggal: {{form.Tanggal}}
              <br/>
              Biaya: {{form.Biaya}}
              <br/>
              Status: {{form.Status}}
              <br/>
              ID Transaksi: {{form.ID_Transaksi}}
            </div>
          </div>

          <div class = "row">
            <div class = "col d-flex justify-content-center">
              <input type="submit" class="btn btn-dark" value="UPDATE">
            </div>
          </div>
        </form>
      </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/8d51ef034d.js" crossorigin="anonymous"></script>
    <script src="{% static 'profil/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'profil/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'profil/js/select2.min.js' %}"></script></body>
</html>